# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'interface', 'classify_image']

# %% app.ipynb 1
from fastai.vision.all import *
import PIL.Image
PIL.Image.MAX_IMAGE_PIXELS = None
from PIL import Image

import gradio as gr

# %% app.ipynb 2
learn = load_learner('tumorClassifier.pkl')

# %% app.ipynb 3
categories=('Glioma','Meningioma','Pituitary tumor')

def classify_image(img):
    pred,indx,probs=learn.predict(img)
    return dict(zip(categories,map(float,probs)))


# %% app.ipynb 4
image=gr.inputs.Image(shape=(512,512))
label=gr.outputs.Label()
examples=['imagesExample/1.jpeg', 'imagesExample/2.jpg', 'imagesExample/3.png','imagesExample/a.jpg','imagesExample/b.jpg'
,'imagesExample/c.jpg','imagesExample/d.jpg','imagesExample/e.jpg','imagesExample/f.jpg']

interface=gr.Interface(fn=classify_image, inputs=image ,outputs=label,examples=examples)
interface.launch(inline=False)
